-- Sample products for all categories
-- Run this after setting up your Supabase database

-- First, insert some sample brands
INSERT INTO brands (name, description, website, logo) VALUES
('SLEEP COMFORT', 'Premium sleep solutions for ultimate comfort', 'https://sleepcomfort.com', '/placeholder.svg'),
('SLEEP LUXURY', 'Luxury sleep products for discerning customers', 'https://sleepluxury.com', '/placeholder.svg'),
('FRAME STYLE', 'Modern bed frames and furniture', 'https://framestyle.com', '/placeholder.svg'),
('COMFORT PLUS', 'Comfortable furniture for modern homes', 'https://comfortplus.com', '/placeholder.svg'),
('PILLOW COMFORT', 'Premium pillows for better sleep', 'https://pillowcomfort.com', '/placeholder.svg')
ON CONFLICT (name) DO NOTHING;

-- Mattresses
INSERT INTO mattresses (name, slug, brand_id, original_price, current_price, monthly_price, main_image, images, short_description, long_description, mattress_type, firmness_level, firmness_description, firmness_scale_image, reasons_to_buy, sizes, colors, features, materials, dimensions, rating, review_count, in_stock, stock_quantity, featured, on_sale, dispatch_time, setup_service, setup_cost, free_delivery, product_questions, warranty_info, care_instructions, care_image, filter_mattress_type, filter_firmness, filter_sizes, filter_features, filter_brand, filter_material, filter_min_price, filter_max_price, filter_in_store, filter_on_sale) VALUES
(
  'Premium Memory Foam Mattress',
  'premium-memory-foam-mattress',
  (SELECT id FROM brands WHERE name = 'SLEEP COMFORT'),
  599.00,
  509.15,
  42,
  '/mattress-image.svg',
  ARRAY['/mattress-image.svg'],
  'Premium memory foam mattress for ultimate comfort and support.',
  'Experience the ultimate in sleep comfort and support with our premium memory foam mattress featuring advanced temperature regulation and motion isolation technology.',
  'Memory Foam',
  5,
  'Medium Soft',
  '/placeholder.svg',
  ARRAY['Premium Quality', 'Advanced Technology', 'Expert Craftsmanship'],
  ARRAY['Single', 'Double', 'King', 'Super King'],
  ARRAY['White', 'Gray', 'Beige'],
  ARRAY['Memory Foam', 'Temperature Regulation', 'Motion Isolation'],
  ARRAY['Memory Foam', 'Premium Fabric'],
  '{"height": "25cm", "length": "200cm", "width": "150cm", "weight_capacity": "150kg"}',
  4.7,
  203,
  true,
  50,
  true,
  true,
  'Tomorrow',
  true,
  49,
  false,
  '[{"question": "What is the warranty period?", "answer": "10 years comprehensive warranty"}, {"question": "How long does delivery take?", "answer": "Free delivery tomorrow"}]',
  '{"period": "10 Years", "coverage": "Comprehensive warranty covering manufacturing defects", "exclusions": "Normal wear and tear"}',
  'Regular vacuuming and spot cleaning recommended. Professional cleaning every 6 months.',
  '/placeholder.svg',
  ARRAY['Memory Foam'],
  ARRAY['Medium Soft'],
  ARRAY['King'],
  ARRAY['Premium Quality', 'Advanced Technology'],
  ARRAY['SLEEP COMFORT'],
  ARRAY['Memory Foam', 'Premium Fabric'],
  400,
  600,
  true,
  true
),
(
  'Luxury Hybrid Mattress',
  'luxury-hybrid-mattress',
  (SELECT id FROM brands WHERE name = 'SLEEP LUXURY'),
  799.00,
  679.15,
  57,
  '/mattress-image.svg',
  ARRAY['/mattress-image.svg'],
  'Luxury hybrid mattress combining pocket springs with memory foam.',
  'Our luxury hybrid mattress combines the best of both worlds - supportive pocket springs with contouring memory foam for the perfect balance of comfort and support.',
  'Hybrid',
  7,
  'Medium Firm',
  '/placeholder.svg',
  ARRAY['Hybrid Technology', 'Premium Quality', 'Expert Craftsmanship'],
  ARRAY['Single', 'Double', 'King', 'Super King'],
  ARRAY['White', 'Gray'],
  ARRAY['Hybrid Technology', 'Pocket Springs', 'Memory Foam', 'Edge Support'],
  ARRAY['Pocket Springs', 'Memory Foam', 'Premium Fabric'],
  '{"height": "30cm", "length": "200cm", "width": "150cm", "weight_capacity": "200kg"}',
  4.9,
  156,
  true,
  30,
  true,
  true,
  'Tomorrow',
  true,
  49,
  false,
  '[{"question": "What is the firmness level?", "answer": "Medium Firm (7/10)"}, {"question": "Does it have edge support?", "answer": "Yes, reinforced edge support for full mattress usage"}]',
  '{"period": "15 Years", "coverage": "Comprehensive warranty covering manufacturing defects", "exclusions": "Normal wear and tear"}',
  'Regular vacuuming with upholstery attachment. Spot clean with mild detergent.',
  '/placeholder.svg',
  ARRAY['Hybrid'],
  ARRAY['Medium Firm'],
  ARRAY['King'],
  ARRAY['Hybrid Technology', 'Premium Quality'],
  ARRAY['SLEEP LUXURY'],
  ARRAY['Pocket Springs', 'Memory Foam'],
  600,
  800,
  true,
  true
);

-- Beds
INSERT INTO beds (name, slug, brand_id, original_price, current_price, monthly_price, main_image, images, short_description, long_description, bed_type, style, reasons_to_buy, sizes, colors, features, materials, dimensions, rating, review_count, in_stock, stock_quantity, featured, on_sale, dispatch_time, setup_service, setup_cost, free_delivery, product_questions, warranty_info, care_instructions, care_image, filter_mattress_type, filter_firmness, filter_sizes, filter_features, filter_brand, filter_material, filter_min_price, filter_max_price, filter_in_store, filter_on_sale) VALUES
(
  'Modern Platform Bed',
  'modern-platform-bed',
  (SELECT id FROM brands WHERE name = 'FRAME STYLE'),
  299.00,
  249.00,
  21,
  '/mattress-image.svg',
  ARRAY['/mattress-image.svg'],
  'Modern platform bed with clean lines and storage.',
  'Contemporary platform bed featuring a sleek design with built-in storage drawers. Perfect for modern bedrooms.',
  'Platform Bed',
  'Modern',
  ARRAY['Modern Design', 'Storage Space', 'Quality Construction'],
  ARRAY['Double', 'King', 'Super King'],
  ARRAY['Oak', 'Walnut', 'White'],
  ARRAY['Platform design', 'Wooden construction', 'Easy assembly', 'Storage space'],
  ARRAY['Solid Wood', 'MDF'],
  '{"height": "40cm", "length": "200cm", "width": "150cm", "weight_capacity": "300kg"}',
  4.6,
  234,
  true,
  25,
  true,
  true,
  'Tomorrow',
  true,
  29,
  false,
  '[{"question": "What material is the frame made of?", "answer": "Solid wood with MDF panels"}, {"question": "Does it include storage?", "answer": "Yes, built-in storage drawers"}]',
  '{"period": "5 Years", "coverage": "Frame and structure warranty", "exclusions": "Normal wear and tear"}',
  'Dust regularly with a soft cloth. Avoid harsh chemicals.',
  '/placeholder.svg',
  ARRAY['Platform'],
  ARRAY[],
  ARRAY['King'],
  ARRAY['Modern Design', 'Storage Space'],
  ARRAY['FRAME STYLE'],
  ARRAY['Solid Wood', 'MDF'],
  200,
  300,
  true,
  true
);

-- Sofas
INSERT INTO sofas (name, slug, brand_id, original_price, current_price, monthly_price, main_image, images, short_description, long_description, sofa_type, style, reasons_to_buy, sizes, colors, features, materials, dimensions, rating, review_count, in_stock, stock_quantity, featured, on_sale, dispatch_time, setup_service, setup_cost, free_delivery, product_questions, warranty_info, care_instructions, care_image, filter_mattress_type, filter_firmness, filter_sizes, filter_features, filter_brand, filter_material, filter_min_price, filter_max_price, filter_in_store, filter_on_sale) VALUES
(
  'Premium Sectional Sofa',
  'premium-sectional-sofa',
  (SELECT id FROM brands WHERE name = 'COMFORT PLUS'),
  899.00,
  764.15,
  64,
  '/sofa.jpeg',
  ARRAY['/sofa.jpeg'],
  'Premium sectional sofa with deep seating and reclining features.',
  'Luxurious sectional sofa offering ultimate comfort with deep seating, premium fabric, and optional reclining seats for the perfect relaxation experience.',
  'Sectional',
  'Modern',
  ARRAY['Premium Quality', 'Comfortable Seating', 'Versatile Design'],
  ARRAY['3-Seater', '4-Seater', '5-Seater'],
  ARRAY['Gray', 'Beige', 'Navy'],
  ARRAY['Sectional design', 'Premium fabric', 'Deep seating', 'Reclining seats'],
  ARRAY['Premium Fabric', 'High-Density Foam', 'Solid Wood Frame'],
  '{"height": "85cm", "length": "280cm", "width": "180cm", "weight_capacity": "400kg"}',
  4.8,
  189,
  true,
  15,
  true,
  true,
  'Tomorrow',
  true,
  49,
  false,
  '[{"question": "What fabric options are available?", "answer": "Gray, Beige, and Navy premium fabrics"}, {"question": "Does it recline?", "answer": "Yes, optional reclining seats available"}]',
  '{"period": "5 Years", "coverage": "Frame and mechanism warranty", "exclusions": "Fabric wear and tear"}',
  'Vacuum regularly and spot clean with mild detergent.',
  '/placeholder.svg',
  ARRAY['Sectional'],
  ARRAY[],
  ARRAY['4-Seater'],
  ARRAY['Premium Quality', 'Comfortable Seating'],
  ARRAY['COMFORT PLUS'],
  ARRAY['Premium Fabric', 'High-Density Foam'],
  700,
  900,
  true,
  true
);

-- Pillows
INSERT INTO pillows (name, slug, brand_id, original_price, current_price, monthly_price, main_image, images, short_description, long_description, pillow_type, style, reasons_to_buy, sizes, colors, features, materials, dimensions, rating, review_count, in_stock, stock_quantity, featured, on_sale, dispatch_time, setup_service, setup_cost, free_delivery, product_questions, warranty_info, care_instructions, care_image, filter_mattress_type, filter_firmness, filter_sizes, filter_features, filter_brand, filter_material, filter_min_price, filter_max_price, filter_in_store, filter_on_sale) VALUES
(
  'Memory Foam Pillow',
  'memory-foam-pillow',
  (SELECT id FROM brands WHERE name = 'PILLOW COMFORT'),
  79.00,
  67.15,
  6,
  '/mattress-image.svg',
  ARRAY['/mattress-image.svg'],
  'Memory foam pillow with temperature regulating properties.',
  'Premium memory foam pillow that contours to your head and neck for optimal support while regulating temperature for a cool, comfortable sleep.',
  'Memory Foam',
  'Modern',
  ARRAY['Memory Foam', 'Temperature Regulating', 'Hypoallergenic'],
  ARRAY['Standard', 'King'],
  ARRAY['White', 'Gray'],
  ARRAY['Memory foam', 'Hypoallergenic', 'Temperature regulating', 'Washable cover'],
  ARRAY['Memory Foam', 'Polyester Cover'],
  '{"height": "12cm", "length": "50cm", "width": "30cm", "weight_capacity": "5kg"}',
  4.7,
  156,
  true,
  100,
  true,
  true,
  'Tomorrow',
  false,
  NULL,
  false,
  '[{"question": "Is it machine washable?", "answer": "The cover is machine washable, pillow core should be spot cleaned"}, {"question": "What firmness is it?", "answer": "Medium firmness for optimal support"}]',
  '{"period": "2 Years", "coverage": "Manufacturing defects", "exclusions": "Normal wear and tear"}',
  'Wash cover in cold water, air dry. Spot clean pillow core.',
  '/placeholder.svg',
  ARRAY['Memory Foam'],
  ARRAY[],
  ARRAY['Standard'],
  ARRAY['Memory Foam', 'Temperature Regulating'],
  ARRAY['PILLOW COMFORT'],
  ARRAY['Memory Foam', 'Polyester'],
  50,
  100,
  true,
  true
);
