-- Comprehensive Test Data for All Categories
-- Run this after executing the database schema in Supabase

-- First, let's add some additional brands for variety
INSERT INTO brands (name, description, website, logo) VALUES
('SLEEP COMFORT', 'Premium sleep solutions for ultimate comfort', 'https://sleepcomfort.com', '/placeholder.svg'),
('SLEEP LUXURY', 'Luxury sleep products for discerning customers', 'https://sleepluxury.com', '/placeholder.svg'),
('FRAME STYLE', 'Modern bed frames and furniture', 'https://framestyle.com', '/placeholder.svg'),
('COMFORT PLUS', 'Comfortable furniture for modern homes', 'https://comfortplus.com', '/placeholder.svg'),
('PILLOW COMFORT', 'Premium pillows for better sleep', 'https://pillowcomfort.com', '/placeholder.svg'),
('TOPPER PRO', 'Professional mattress toppers', 'https://topperpro.com', '/placeholder.svg'),
('BUNK MASTER', 'Space-saving bunk bed solutions', 'https://bunkmaster.com', '/placeholder.svg'),
('KIDS DREAM', 'Furniture and bedding for children', 'https://kidsdream.com', '/placeholder.svg')
ON CONFLICT (name) DO NOTHING;

-- ============================================================================
-- MATTRESSES TEST DATA
-- ============================================================================

INSERT INTO mattresses (name, slug, brand_id, original_price, current_price, monthly_price, main_image, images, short_description, long_description, description_paragraph_1, description_paragraph_2, description_paragraph_3, description_image_1, description_image_2, description_image_3, mattress_type, firmness_level, firmness_description, firmness_scale_image, reasons_to_buy, sizes, colors, features, materials, dimensions, rating, review_count, in_stock, stock_quantity, featured, on_sale, dispatch_time, setup_service, setup_cost, free_delivery, product_questions, warranty_info, care_instructions, care_image, filter_mattress_type, filter_firmness, filter_sizes, filter_features, filter_brand, filter_material, filter_min_price, filter_max_price, filter_in_store, filter_on_sale, meta_title, meta_description, meta_keywords) VALUES
(
  'Premium Memory Foam Mattress',
  'premium-memory-foam-mattress',
  (SELECT id FROM brands WHERE name = 'SLEEP COMFORT'),
  599.00,
  509.15,
  42,
  '/mattress-image.svg',
  ARRAY['/mattress-image.svg', '/placeholder.svg', '/placeholder.svg'],
  'Premium memory foam mattress for ultimate comfort and support.',
  'Experience the ultimate in sleep comfort and support with our premium memory foam mattress featuring advanced temperature regulation and motion isolation technology.',
  'Our premium memory foam mattress is designed with advanced temperature regulation technology that keeps you cool throughout the night. The open-cell structure allows for optimal airflow, preventing heat buildup.',
  'The memory foam contours perfectly to your body shape, providing personalized support and pressure relief. This reduces tossing and turning, allowing you to achieve deeper, more restful sleep.',
  'Built with high-density memory foam that maintains its shape and support for years. The mattress includes motion isolation technology, so your partner''s movements won''t disturb your sleep.',
  '/placeholder.svg',
  '/placeholder.svg',
  '/placeholder.svg',
  'Memory Foam',
  5,
  'Medium Soft',
  '/placeholder.svg',
  ARRAY['Premium Quality', 'Advanced Technology', 'Expert Craftsmanship', 'Temperature Regulation', 'Motion Isolation'],
  ARRAY['Single', 'Double', 'King', 'Super King'],
  ARRAY['White', 'Gray', 'Beige'],
  ARRAY['Memory Foam', 'Temperature Regulation', 'Motion Isolation', 'Pressure Relief', 'Cooling Technology'],
  ARRAY['Memory Foam', 'Premium Fabric', 'Cooling Gel'],
  '{"height": "25cm", "length": "200cm", "width": "150cm", "weight_capacity": "150kg"}',
  4.7,
  203,
  true,
  50,
  true,
  true,
  'Tomorrow',
  true,
  49,
  false,
  '[{"question": "What is the warranty period?", "answer": "10 years comprehensive warranty"}, {"question": "How long does delivery take?", "answer": "Free delivery tomorrow"}, {"question": "Is it hypoallergenic?", "answer": "Yes, made with hypoallergenic materials"}]',
  '{"period": "10 Years", "coverage": "Comprehensive warranty covering manufacturing defects", "exclusions": "Normal wear and tear"}',
  'Regular vacuuming and spot cleaning recommended. Professional cleaning every 6 months. Avoid direct sunlight and moisture.',
  '/placeholder.svg',
  ARRAY['Memory Foam'],
  ARRAY['Medium Soft'],
  ARRAY['King'],
  ARRAY['Premium Quality', 'Advanced Technology', 'Temperature Regulation'],
  ARRAY['SLEEP COMFORT'],
  ARRAY['Memory Foam', 'Premium Fabric'],
  400,
  600,
  true,
  true,
  'Premium Memory Foam Mattress - Ultimate Comfort & Support',
  'Discover the ultimate sleep experience with our premium memory foam mattress featuring advanced temperature regulation and motion isolation technology.',
  ARRAY['memory foam', 'mattress', 'premium', 'comfort', 'support', 'cooling']
),
(
  'Luxury Hybrid Mattress',
  'luxury-hybrid-mattress',
  (SELECT id FROM brands WHERE name = 'SLEEP LUXURY'),
  799.00,
  679.15,
  57,
  '/mattress-image.svg',
  ARRAY['/mattress-image.svg', '/placeholder.svg', '/placeholder.svg'],
  'Luxury hybrid mattress combining pocket springs with memory foam.',
  'Our luxury hybrid mattress combines the best of both worlds - supportive pocket springs with contouring memory foam for the perfect balance of comfort and support.',
  'The hybrid design features individually wrapped pocket springs that provide targeted support and excellent motion isolation. Each spring moves independently, adapting to your body''s contours.',
  'Topped with premium memory foam that offers pressure relief and temperature regulation. The combination creates a mattress that''s both supportive and comfortable.',
  'Built with reinforced edge support for full mattress usage and enhanced durability. The hybrid construction ensures long-lasting performance and consistent comfort.',
  '/placeholder.svg',
  '/placeholder.svg',
  '/placeholder.svg',
  'Hybrid',
  7,
  'Medium Firm',
  '/placeholder.svg',
  ARRAY['Hybrid Technology', 'Premium Quality', 'Expert Craftsmanship', 'Edge Support', 'Motion Isolation'],
  ARRAY['Single', 'Double', 'King', 'Super King'],
  ARRAY['White', 'Gray'],
  ARRAY['Hybrid Technology', 'Pocket Springs', 'Memory Foam', 'Edge Support', 'Motion Isolation'],
  ARRAY['Pocket Springs', 'Memory Foam', 'Premium Fabric', 'Reinforced Edges'],
  '{"height": "30cm", "length": "200cm", "width": "150cm", "weight_capacity": "200kg"}',
  4.9,
  156,
  true,
  30,
  true,
  true,
  'Tomorrow',
  true,
  49,
  false,
  '[{"question": "What is the firmness level?", "answer": "Medium Firm (7/10)"}, {"question": "Does it have edge support?", "answer": "Yes, reinforced edge support for full mattress usage"}, {"question": "How many pocket springs?", "answer": "1000+ individually wrapped pocket springs"}]',
  '{"period": "15 Years", "coverage": "Comprehensive warranty covering manufacturing defects", "exclusions": "Normal wear and tear"}',
  'Regular vacuuming with upholstery attachment. Spot clean with mild detergent. Rotate mattress every 3 months for even wear.',
  '/placeholder.svg',
  ARRAY['Hybrid'],
  ARRAY['Medium Firm'],
  ARRAY['King'],
  ARRAY['Hybrid Technology', 'Premium Quality', 'Edge Support'],
  ARRAY['SLEEP LUXURY'],
  ARRAY['Pocket Springs', 'Memory Foam'],
  600,
  800,
  true,
  true,
  'Luxury Hybrid Mattress - Best of Both Worlds',
  'Experience the perfect balance of support and comfort with our luxury hybrid mattress featuring pocket springs and memory foam.',
  ARRAY['hybrid', 'mattress', 'luxury', 'pocket springs', 'memory foam', 'edge support']
),
(
  'Cooling Gel Mattress',
  'cooling-gel-mattress',
  (SELECT id FROM brands WHERE name = 'SLEEP COMFORT'),
  449.00,
  381.65,
  32,
  '/mattress-image.svg',
  ARRAY['/mattress-image.svg', '/placeholder.svg'],
  'Advanced cooling gel mattress for temperature regulation.',
  'Stay cool and comfortable all night with our advanced cooling gel mattress that regulates temperature and provides exceptional comfort.',
  'The cooling gel technology actively draws heat away from your body, maintaining an optimal sleep temperature throughout the night.',
  'Combined with memory foam for pressure relief and motion isolation, ensuring you and your partner enjoy undisturbed sleep.',
  'The breathable cover enhances airflow and the gel-infused foam provides long-lasting cooling properties.',
  '/placeholder.svg',
  '/placeholder.svg',
  '/placeholder.svg',
  'Gel Foam',
  6,
  'Medium',
  '/placeholder.svg',
  ARRAY['Cooling Technology', 'Temperature Regulation', 'Motion Isolation', 'Pressure Relief'],
  ARRAY['Single', 'Double', 'King', 'Super King'],
  ARRAY['Blue', 'Gray'],
  ARRAY['Cooling Gel', 'Temperature Regulation', 'Motion Isolation', 'Pressure Relief'],
  ARRAY['Cooling Gel', 'Memory Foam', 'Breathable Fabric'],
  '{"height": "22cm", "length": "200cm", "width": "150cm", "weight_capacity": "120kg"}',
  4.6,
  89,
  true,
  75,
  false,
  true,
  'Tomorrow',
  false,
  NULL,
  false,
  '[{"question": "How does the cooling work?", "answer": "Gel technology actively draws heat away from your body"}, {"question": "Is it suitable for hot sleepers?", "answer": "Yes, specifically designed for temperature regulation"}]',
  '{"period": "8 Years", "coverage": "Manufacturing defects and materials", "exclusions": "Normal wear and tear"}',
  'Vacuum regularly and spot clean. Avoid harsh chemicals. The cooling properties are built into the foam and will last the lifetime of the mattress.',
  '/placeholder.svg',
  ARRAY['Gel Foam'],
  ARRAY['Medium'],
  ARRAY['King'],
  ARRAY['Cooling Technology', 'Temperature Regulation'],
  ARRAY['SLEEP COMFORT'],
  ARRAY['Cooling Gel', 'Memory Foam'],
  300,
  500,
  true,
  true,
  'Cooling Gel Mattress - Stay Cool All Night',
  'Advanced cooling gel technology keeps you comfortable with temperature regulation and pressure relief.',
  ARRAY['cooling', 'gel', 'mattress', 'temperature regulation', 'memory foam']
);

-- ============================================================================
-- BEDS TEST DATA
-- ============================================================================

INSERT INTO beds (name, slug, brand_id, original_price, current_price, monthly_price, main_image, images, short_description, long_description, description_paragraph_1, description_paragraph_2, description_paragraph_3, description_image_1, description_image_2, description_image_3, bed_type, style, reasons_to_buy, sizes, colors, features, materials, dimensions, rating, review_count, in_stock, stock_quantity, featured, on_sale, dispatch_time, setup_service, setup_cost, free_delivery, product_questions, warranty_info, care_instructions, care_image, filter_bed_type, filter_style, filter_sizes, filter_features, filter_brand, filter_material, filter_min_price, filter_max_price, filter_in_store, filter_on_sale, meta_title, meta_description, meta_keywords) VALUES
(
  'Modern Platform Bed',
  'modern-platform-bed',
  (SELECT id FROM brands WHERE name = 'FRAME STYLE'),
  299.00,
  249.00,
  21,
  '/mattress-image.svg',
  ARRAY['/mattress-image.svg', '/placeholder.svg'],
  'Modern platform bed with clean lines and storage.',
  'Contemporary platform bed featuring a sleek design with built-in storage drawers. Perfect for modern bedrooms.',
  'The modern platform design eliminates the need for a box spring, providing a clean, low-profile look that works perfectly in contemporary bedrooms.',
  'Built-in storage drawers offer convenient space for bedding, clothing, or other items, making this bed both stylish and functional.',
  'Constructed from premium materials with attention to detail, ensuring durability and long-lasting beauty.',
  '/placeholder.svg',
  '/placeholder.svg',
  '/placeholder.svg',
  'Platform Bed',
  'Modern',
  ARRAY['Modern Design', 'Storage Space', 'Quality Construction', 'No Box Spring Needed'],
  ARRAY['Double', 'King', 'Super King'],
  ARRAY['Oak', 'Walnut', 'White'],
  ARRAY['Platform design', 'Wooden construction', 'Easy assembly', 'Storage space', 'No box spring needed'],
  ARRAY['Solid Wood', 'MDF', 'Metal Hardware'],
  '{"height": "40cm", "length": "200cm", "width": "150cm", "weight_capacity": "300kg"}',
  4.6,
  234,
  true,
  25,
  true,
  true,
  'Tomorrow',
  true,
  29,
  false,
  '[{"question": "What material is the frame made of?", "answer": "Solid wood with MDF panels"}, {"question": "Does it include storage?", "answer": "Yes, built-in storage drawers"}, {"question": "Does it need a box spring?", "answer": "No, platform design eliminates the need for a box spring"}]',
  '{"period": "5 Years", "coverage": "Frame and structure warranty", "exclusions": "Normal wear and tear"}',
  'Dust regularly with a soft cloth. Avoid harsh chemicals. Check hardware tightness periodically.',
  '/placeholder.svg',
  ARRAY['Platform Bed'],
  ARRAY['Modern'],
  ARRAY['King'],
  ARRAY['Modern Design', 'Storage Space', 'No Box Spring'],
  ARRAY['FRAME STYLE'],
  ARRAY['Solid Wood', 'MDF'],
  200,
  300,
  true,
  true,
  'Modern Platform Bed with Storage - Contemporary Design',
  'Sleek modern platform bed with built-in storage drawers. No box spring needed for a clean, low-profile look.',
  ARRAY['platform bed', 'modern', 'storage', 'contemporary', 'no box spring']
),
(
  'Storage Bed Frame',
  'storage-bed-frame',
  (SELECT id FROM brands WHERE name = 'FRAME STYLE'),
  399.00,
  339.15,
  28,
  '/mattress-image.svg',
  ARRAY['/mattress-image.svg', '/placeholder.svg'],
  'Ottoman lift storage bed with premium fabric upholstery.',
  'Maximize your bedroom space with our ottoman lift storage bed featuring premium fabric upholstery and easy-access storage.',
  'The ottoman lift mechanism provides easy access to the large storage area beneath the mattress, perfect for storing seasonal clothing or extra bedding.',
  'Premium fabric upholstery adds luxury to your bedroom while the sturdy construction ensures years of reliable use.',
  'Available in multiple colors to match any bedroom decor, this bed combines functionality with style.',
  '/placeholder.svg',
  '/placeholder.svg',
  '/placeholder.svg',
  'Storage Bed',
  'Contemporary',
  ARRAY['Storage Space', 'Ottoman Lift', 'Premium Fabric', 'Space Saving'],
  ARRAY['Double', 'King'],
  ARRAY['Gray', 'Beige', 'Navy'],
  ARRAY['Ottoman lift', 'Built-in storage', 'Fabric upholstery', 'Easy access', 'Space saving'],
  ARRAY['Premium Fabric', 'MDF', 'Metal Hardware', 'Lift Mechanism'],
  '{"height": "45cm", "length": "200cm", "width": "150cm", "weight_capacity": "250kg"}',
  4.5,
  189,
  true,
  20,
  false,
  true,
  'Tomorrow',
  true,
  39,
  false,
  '[{"question": "How much storage space?", "answer": "Large storage area beneath the mattress"}, {"question": "Is it easy to lift?", "answer": "Yes, smooth ottoman lift mechanism"}, {"question": "What fabric options?", "answer": "Gray, Beige, and Navy premium fabrics"}]',
  '{"period": "3 Years", "coverage": "Frame and mechanism warranty", "exclusions": "Fabric wear and tear"}',
  'Vacuum fabric regularly. Spot clean with mild detergent. Check lift mechanism periodically.',
  '/placeholder.svg',
  ARRAY['Storage Bed'],
  ARRAY['Contemporary'],
  ARRAY['King'],
  ARRAY['Storage Space', 'Ottoman Lift', 'Premium Fabric'],
  ARRAY['FRAME STYLE'],
  ARRAY['Premium Fabric', 'MDF'],
  300,
  400,
  true,
  true,
  'Storage Bed Frame - Ottoman Lift with Premium Fabric',
  'Maximize bedroom space with our ottoman lift storage bed featuring premium fabric upholstery.',
  ARRAY['storage bed', 'ottoman lift', 'fabric', 'contemporary', 'space saving']
);

-- ============================================================================
-- SOFAS TEST DATA
-- ============================================================================

INSERT INTO sofas (name, slug, brand_id, original_price, current_price, monthly_price, main_image, images, short_description, long_description, description_paragraph_1, description_image_1, description_paragraph_2, description_image_2, description_paragraph_3, description_image_3, sofa_type, style, reasons_to_buy, sizes, colors, features, materials, dimensions, rating, review_count, in_stock, stock_quantity, featured, on_sale, dispatch_time, setup_service, setup_cost, free_delivery, product_questions, warranty_info, care_instructions, care_image, filter_sofa_type, filter_style, filter_sizes, filter_features, filter_brand, filter_material, filter_min_price, filter_max_price, filter_in_store, filter_on_sale, meta_title, meta_description, meta_keywords) VALUES
(
  'Premium Sectional Sofa',
  'premium-sectional-sofa',
  (SELECT id FROM brands WHERE name = 'COMFORT PLUS'),
  899.00,
  764.15,
  64,
  '/sofa.jpeg',
  ARRAY['/sofa.jpeg', '/placeholder.svg', '/placeholder.svg'],
  'Premium sectional sofa with deep seating and reclining features.',
  'Luxurious sectional sofa offering ultimate comfort with deep seating, premium fabric, and optional reclining seats for the perfect relaxation experience.',
  'The sectional design provides flexible seating arrangements that can be configured to fit any living room layout. Perfect for both intimate gatherings and family movie nights.',
  '/placeholder.svg',
  'Deep seating with high-density foam cushions ensures maximum comfort for extended periods. The premium fabric is both durable and soft to the touch.',
  '/placeholder.svg',
  'Optional reclining seats add an extra level of luxury and functionality. Built with solid wood frames for durability and long-lasting performance.',
  '/placeholder.svg',
  'Sectional',
  'Modern',
  ARRAY['Premium Quality', 'Comfortable Seating', 'Versatile Design', 'Reclining Options'],
  ARRAY['3-Seater', '4-Seater', '5-Seater'],
  ARRAY['Gray', 'Beige', 'Navy'],
  ARRAY['Sectional design', 'Premium fabric', 'Deep seating', 'Reclining seats', 'Modular configuration'],
  ARRAY['Premium Fabric', 'High-Density Foam', 'Solid Wood Frame', 'Metal Hardware'],
  '{"height": "85cm", "length": "280cm", "width": "180cm", "weight_capacity": "400kg"}',
  4.8,
  189,
  true,
  15,
  true,
  true,
  'Tomorrow',
  true,
  49,
  false,
  '[{"question": "What fabric options are available?", "answer": "Gray, Beige, and Navy premium fabrics"}, {"question": "Does it recline?", "answer": "Yes, optional reclining seats available"}, {"question": "Is it modular?", "answer": "Yes, sectional design allows for flexible configuration"}]',
  '{"period": "5 Years", "coverage": "Frame and mechanism warranty", "exclusions": "Fabric wear and tear"}',
  'Vacuum regularly and spot clean with mild detergent. Professional cleaning recommended annually.',
  '/placeholder.svg',
  ARRAY['Sectional'],
  ARRAY['Modern'],
  ARRAY['4-Seater'],
  ARRAY['Premium Quality', 'Comfortable Seating', 'Reclining Options'],
  ARRAY['COMFORT PLUS'],
  ARRAY['Premium Fabric', 'High-Density Foam'],
  700,
  900,
  true,
  true,
  'Premium Sectional Sofa - Luxury Comfort & Style',
  'Luxurious sectional sofa with deep seating, premium fabric, and optional reclining seats for ultimate comfort.',
  ARRAY['sectional sofa', 'premium', 'reclining', 'modern', 'comfortable']
),
(
  'Convertible Sleeper Sofa',
  'convertible-sleeper-sofa',
  (SELECT id FROM brands WHERE name = 'COMFORT PLUS'),
  599.00,
  509.15,
  42,
  '/sofa.jpeg',
  ARRAY['/sofa.jpeg', '/placeholder.svg'],
  'Versatile convertible sofa that transforms into a comfortable bed.',
  'Perfect for small spaces and guest rooms, this convertible sofa offers comfortable seating by day and a restful bed by night.',
  'The easy-pull mechanism smoothly converts the sofa into a full-size bed in seconds, making it perfect for unexpected guests or small apartments.',
  '/placeholder.svg',
  'High-quality foam cushions provide comfortable seating and supportive sleeping surface. The durable fabric withstands daily use.',
  '/placeholder.svg',
  'Compact design fits perfectly in small spaces while offering maximum functionality for modern living.',
  '/placeholder.svg',
  'Sleeper Sofa',
  'Contemporary',
  ARRAY['Space Saving', 'Dual Function', 'Easy Conversion', 'Comfortable'],
  ARRAY['2-Seater', '3-Seater'],
  ARRAY['Gray', 'Beige'],
  ARRAY['Convertible design', 'Easy pull mechanism', 'Comfortable seating', 'Full-size bed', 'Space saving'],
  ARRAY['Durable Fabric', 'High-Density Foam', 'Metal Frame', 'Pull Mechanism'],
  '{"height": "85cm", "length": "200cm", "width": "85cm", "weight_capacity": "200kg"}',
  4.4,
  156,
  true,
  25,
  false,
  true,
  'Tomorrow',
  true,
  39,
  false,
  '[{"question": "How easy is it to convert?", "answer": "Very easy, smooth pull mechanism"}, {"question": "What size bed does it make?", "answer": "Full-size bed when converted"}, {"question": "Is it comfortable to sleep on?", "answer": "Yes, high-quality foam provides good support"}]',
  '{"period": "3 Years", "coverage": "Frame and mechanism warranty", "exclusions": "Fabric wear and tear"}',
  'Regular vacuuming and spot cleaning. Check mechanism periodically. Professional cleaning recommended.',
  '/placeholder.svg',
  ARRAY['Sleeper Sofa'],
  ARRAY['Contemporary'],
  ARRAY['3-Seater'],
  ARRAY['Space Saving', 'Dual Function', 'Easy Conversion'],
  ARRAY['COMFORT PLUS'],
  ARRAY['Durable Fabric', 'High-Density Foam'],
  450,
  600,
  true,
  true,
  'Convertible Sleeper Sofa - Space Saving Solution',
  'Versatile convertible sofa that transforms into a comfortable bed, perfect for small spaces and guest rooms.',
  ARRAY['convertible sofa', 'sleeper sofa', 'space saving', 'guest room', 'small apartment']
);

-- ============================================================================
-- PILLOWS TEST DATA
-- ============================================================================

INSERT INTO pillows (name, slug, brand_id, original_price, current_price, monthly_price, main_image, images, short_description, long_description, description_paragraph_1, description_image_1, description_paragraph_2, description_image_2, description_paragraph_3, description_image_3, pillow_type, firmness, reasons_to_buy, sizes, colors, features, materials, dimensions, rating, review_count, in_stock, stock_quantity, featured, on_sale, dispatch_time, setup_service, setup_cost, free_delivery, product_questions, warranty_info, care_instructions, care_image, filter_pillow_type, filter_firmness, filter_sizes, filter_features, filter_brand, filter_material, filter_min_price, filter_max_price, filter_in_store, filter_on_sale, meta_title, meta_description, meta_keywords) VALUES
(
  'Memory Foam Pillow',
  'memory-foam-pillow',
  (SELECT id FROM brands WHERE name = 'PILLOW COMFORT'),
  79.00,
  67.15,
  6,
  '/mattress-image.svg',
  ARRAY['/mattress-image.svg', '/placeholder.svg'],
  'Memory foam pillow with temperature regulating properties.',
  'Premium memory foam pillow that contours to your head and neck for optimal support while regulating temperature for a cool, comfortable sleep.',
  'The memory foam technology contours perfectly to your head and neck, providing personalized support that reduces pressure points and promotes proper spinal alignment.',
  '/placeholder.svg',
  'Advanced temperature regulation technology keeps you cool throughout the night, preventing heat buildup that can disrupt sleep.',
  '/placeholder.svg',
  'Hypoallergenic materials make this pillow suitable for allergy sufferers, while the washable cover ensures easy maintenance.',
  '/placeholder.svg',
  'Memory Foam',
  'Medium',
  ARRAY['Memory Foam', 'Temperature Regulating', 'Hypoallergenic', 'Pressure Relief'],
  ARRAY['Standard', 'King'],
  ARRAY['White', 'Gray'],
  ARRAY['Memory foam', 'Hypoallergenic', 'Temperature regulating', 'Washable cover', 'Pressure relief'],
  ARRAY['Memory Foam', 'Polyester Cover', 'Cooling Technology'],
  '{"height": "12cm", "length": "50cm", "width": "30cm", "weight_capacity": "5kg"}',
  4.7,
  156,
  true,
  100,
  true,
  true,
  'Tomorrow',
  false,
  NULL,
  false,
  '[{"question": "Is it machine washable?", "answer": "The cover is machine washable, pillow core should be spot cleaned"}, {"question": "What firmness is it?", "answer": "Medium firmness for optimal support"}, {"question": "Is it hypoallergenic?", "answer": "Yes, made with hypoallergenic materials"}]',
  '{"period": "2 Years", "coverage": "Manufacturing defects", "exclusions": "Normal wear and tear"}',
  'Wash cover in cold water, air dry. Spot clean pillow core. Fluff regularly to maintain shape.',
  '/placeholder.svg',
  ARRAY['Memory Foam'],
  ARRAY['Medium'],
  ARRAY['Standard'],
  ARRAY['Memory Foam', 'Temperature Regulating', 'Hypoallergenic'],
  ARRAY['PILLOW COMFORT'],
  ARRAY['Memory Foam', 'Polyester'],
  50,
  100,
  true,
  true,
  'Memory Foam Pillow - Temperature Regulating & Hypoallergenic',
  'Premium memory foam pillow with temperature regulation and hypoallergenic properties for optimal sleep support.',
  ARRAY['memory foam pillow', 'temperature regulating', 'hypoallergenic', 'pressure relief', 'cooling']
),
(
  'Down Alternative Pillow',
  'down-alternative-pillow',
  (SELECT id FROM brands WHERE name = 'PILLOW COMFORT'),
  59.00,
  49.15,
  4,
  '/mattress-image.svg',
  ARRAY['/mattress-image.svg'],
  'Luxurious down alternative pillow with cloud-like softness.',
  'Experience the softness and comfort of down without the allergens. Our down alternative pillow provides the same luxurious feel.',
  'The down alternative filling mimics the softness and loft of natural down, providing a cloud-like sleeping experience without triggering allergies.',
  '/placeholder.svg',
  'Hypoallergenic materials ensure this pillow is suitable for everyone, including those with allergies or sensitivities to natural down.',
  '/placeholder.svg',
  'Easy to care for with machine washable construction that maintains its shape and softness wash after wash.',
  '/placeholder.svg',
  'Down Alternative',
  'Soft',
  ARRAY['Down Alternative', 'Hypoallergenic', 'Cloud-like Softness', 'Machine Washable'],
  ARRAY['Standard', 'King'],
  ARRAY['White'],
  ARRAY['Down alternative', 'Hypoallergenic', 'Cloud-like softness', 'Machine washable', 'Maintains shape'],
  ARRAY['Down Alternative Fiber', 'Cotton Cover', 'Hypoallergenic Material'],
  '{"height": "15cm", "length": "50cm", "width": "30cm", "weight_capacity": "3kg"}',
  4.5,
  98,
  true,
  75,
  false,
  true,
  'Tomorrow',
  false,
  NULL,
  false,
  '[{"question": "Is it really hypoallergenic?", "answer": "Yes, made with hypoallergenic materials"}, {"question": "How soft is it?", "answer": "Very soft, cloud-like feel"}, {"question": "Can I machine wash it?", "answer": "Yes, fully machine washable"}]',
  '{"period": "1 Year", "coverage": "Manufacturing defects", "exclusions": "Normal wear and tear"}',
  'Machine wash in cold water, tumble dry low. Fluff regularly to maintain loft and shape.',
  '/placeholder.svg',
  ARRAY['Down Alternative'],
  ARRAY['Soft'],
  ARRAY['Standard'],
  ARRAY['Down Alternative', 'Hypoallergenic', 'Cloud-like Softness'],
  ARRAY['PILLOW COMFORT'],
  ARRAY['Down Alternative Fiber', 'Cotton'],
  40,
  80,
  true,
  true,
  'Down Alternative Pillow - Hypoallergenic Luxury',
  'Luxurious down alternative pillow with cloud-like softness, hypoallergenic and machine washable.',
  ARRAY['down alternative pillow', 'hypoallergenic', 'soft', 'machine washable', 'luxury']
);

-- ============================================================================
-- TOPPERS TEST DATA
-- ============================================================================

INSERT INTO toppers (name, slug, brand_id, original_price, current_price, monthly_price, main_image, images, short_description, long_description, description_paragraph_1, description_image_1, description_paragraph_2, description_image_2, description_paragraph_3, description_image_3, topper_type, reasons_to_buy, sizes, colors, features, materials, dimensions, rating, review_count, in_stock, stock_quantity, featured, on_sale, dispatch_time, setup_service, setup_cost, free_delivery, product_questions, warranty_info, care_instructions, care_image, filter_topper_type, filter_sizes, filter_features, filter_brand, filter_material, filter_min_price, filter_max_price, filter_in_store, filter_on_sale, meta_title, meta_description, meta_keywords) VALUES
(
  'Memory Foam Topper',
  'memory-foam-topper',
  (SELECT id FROM brands WHERE name = 'TOPPER PRO'),
  129.00,
  109.65,
  9,
  '/mattress-image.svg',
  ARRAY['/mattress-image.svg', '/placeholder.svg'],
  'Premium memory foam topper for enhanced mattress comfort.',
  'Transform your existing mattress with our premium memory foam topper that adds extra comfort and support.',
  'The high-density memory foam contours to your body shape, providing personalized support and pressure relief that can extend the life of your current mattress.',
  '/placeholder.svg',
  'Easy to install and remove, this topper can be used on any mattress size and provides immediate comfort improvement.',
  '/placeholder.svg',
  'Breathable design with cooling properties ensures comfortable sleep without heat buildup.',
  '/placeholder.svg',
  'Memory Foam',
  ARRAY['Enhanced Comfort', 'Pressure Relief', 'Easy Installation', 'Cooling Properties'],
  ARRAY['Single', 'Double', 'King', 'Super King'],
  ARRAY['White', 'Gray'],
  ARRAY['Memory foam', 'Pressure relief', 'Easy installation', 'Cooling properties', 'Breathable'],
  ARRAY['Memory Foam', 'Breathable Fabric', 'Cooling Technology'],
  '{"height": "5cm", "length": "200cm", "width": "150cm", "weight_capacity": "120kg"}',
  4.6,
  134,
  true,
  60,
  false,
  true,
  'Tomorrow',
  false,
  NULL,
  false,
  '[{"question": "How thick is the topper?", "answer": "5cm thickness for optimal comfort"}, {"question": "Is it easy to install?", "answer": "Yes, simply place on top of your mattress"}, {"question": "Will it make my mattress hotter?", "answer": "No, it has cooling properties to prevent heat buildup"}]',
  '{"period": "3 Years", "coverage": "Manufacturing defects", "exclusions": "Normal wear and tear"}',
  'Spot clean only. Air out regularly. Use mattress protector to keep clean.',
  '/placeholder.svg',
  ARRAY['Memory Foam'],
  ARRAY['King'],
  ARRAY['Enhanced Comfort', 'Pressure Relief', 'Cooling Properties'],
  ARRAY['TOPPER PRO'],
  ARRAY['Memory Foam', 'Breathable Fabric'],
  80,
  150,
  true,
  true,
  'Memory Foam Topper - Enhanced Comfort & Support',
  'Transform your mattress with our premium memory foam topper for enhanced comfort and pressure relief.',
  ARRAY['memory foam topper', 'mattress topper', 'comfort', 'pressure relief', 'cooling']
);

-- ============================================================================
-- BUNKBEDS TEST DATA
-- ============================================================================

INSERT INTO bunkbeds (name, slug, brand_id, original_price, current_price, monthly_price, main_image, images, short_description, long_description, description_paragraph_1, description_image_1, description_paragraph_2, description_image_2, description_paragraph_3, description_image_3, bunk_bed_type, reasons_to_buy, sizes, colors, features, materials, dimensions, rating, review_count, in_stock, stock_quantity, featured, on_sale, dispatch_time, setup_service, setup_cost, free_delivery, product_questions, warranty_info, care_instructions, care_image, filter_bunk_bed_type, filter_sizes, filter_features, filter_brand, filter_material, filter_min_price, filter_max_price, filter_in_store, filter_on_sale, meta_title, meta_description, meta_keywords) VALUES
(
  'Classic Wooden Bunk Bed',
  'classic-wooden-bunk-bed',
  (SELECT id FROM brands WHERE name = 'BUNK MASTER'),
  399.00,
  339.15,
  28,
  '/mattress-image.svg',
  ARRAY['/mattress-image.svg', '/placeholder.svg'],
  'Solid wood bunk bed with safety rails and ladder.',
  'Classic wooden bunk bed built with safety in mind, featuring solid wood construction, safety rails, and a sturdy ladder.',
  'Constructed from premium solid wood for durability and stability, this bunk bed provides a safe sleeping solution for children.',
  '/placeholder.svg',
  'Safety rails on both levels and a sturdy ladder ensure secure access and prevent accidents during sleep.',
  '/placeholder.svg',
  'Easy assembly with clear instructions and all necessary hardware included for straightforward setup.',
  '/placeholder.svg',
  'Standard Bunk',
  ARRAY['Solid Wood', 'Safety Rails', 'Sturdy Ladder', 'Easy Assembly'],
  ARRAY['Twin'],
  ARRAY['Natural Wood', 'White', 'Oak'],
  ARRAY['Solid wood construction', 'Safety rails', 'Sturdy ladder', 'Easy assembly', 'Durable'],
  ARRAY['Solid Wood', 'Metal Hardware', 'Safety Rails'],
  '{"height": "160cm", "length": "200cm", "width": "90cm", "weight_capacity": "150kg"}',
  4.6,
  189,
  true,
  30,
  false,
  true,
  'Tomorrow',
  true,
  49,
  false,
  '[{"question": "What age is this suitable for?", "answer": "Recommended for children 6 years and older"}, {"question": "Does it include safety rails?", "answer": "Yes, safety rails on both levels"}, {"question": "What wood is used?", "answer": "Premium solid wood construction"}]',
  '{"period": "5 Years", "coverage": "Frame and structure warranty", "exclusions": "Normal wear and tear"}',
  'Regular dusting with soft cloth. Check hardware tightness monthly. Avoid harsh chemicals.',
  '/placeholder.svg',
  ARRAY['Standard Bunk'],
  ARRAY['Twin'],
  ARRAY['Solid Wood', 'Safety Rails', 'Easy Assembly'],
  ARRAY['BUNK MASTER'],
  ARRAY['Solid Wood', 'Metal Hardware'],
  300,
  400,
  true,
  true,
  'Classic Wooden Bunk Bed - Safe & Durable',
  'Solid wood bunk bed with safety rails and sturdy ladder, perfect for children''s bedrooms.',
  ARRAY['bunk bed', 'wooden', 'safety rails', 'children', 'twin size']
);

-- ============================================================================
-- FREQUENTLY BOUGHT TOGETHER TEST DATA
-- ============================================================================

INSERT INTO frequently_bought_together (product_id, product_category, related_items) VALUES
(
  (SELECT id FROM mattresses WHERE slug = 'premium-memory-foam-mattress'),
  'mattresses',
  '[
    {"image": "/mattress-image.svg", "name": "Memory Foam Pillow", "promotionalText": "Perfect pillow for your memory foam mattress", "discount": "15%"},
    {"image": "/mattress-image.svg", "name": "Mattress Protector", "promotionalText": "Protect your investment", "discount": "20%"},
    {"image": "/mattress-image.svg", "name": "Bedding Set", "promotionalText": "Complete your bedroom look", "discount": "25%"}
  ]'
),
(
  (SELECT id FROM beds WHERE slug = 'modern-platform-bed'),
  'beds',
  '[
    {"image": "/mattress-image.svg", "name": "Premium Mattress", "promotionalText": "Perfect mattress for your platform bed", "discount": "10%"},
    {"image": "/mattress-image.svg", "name": "Bedside Table", "promotionalText": "Complete your bedroom set", "discount": "15%"},
    {"image": "/mattress-image.svg", "name": "Bed Linen", "promotionalText": "Luxury bedding for your new bed", "discount": "20%"}
  ]'
);

-- ============================================================================
-- HOMEPAGE CONTENT TEST DATA
-- ============================================================================

UPDATE homepage_content SET content = '[
  {"title": "Memory Foam", "description": "Ultimate comfort and support", "icon": "🛏️", "image": "/placeholder.svg"},
  {"title": "Hybrid", "description": "Best of both worlds", "icon": "🔄", "image": "/placeholder.svg"},
  {"title": "Innerspring", "description": "Traditional support", "icon": "🌀", "image": "/placeholder.svg"},
  {"title": "Latex", "description": "Natural and durable", "icon": "🌿", "image": "/placeholder.svg"}
]' WHERE section_key = 'mattress_types';

UPDATE homepage_content SET content = '[
  {"title": "Luxury Bedroom", "description": "Transform your space", "image": "/placeholder.svg"},
  {"title": "Modern Living", "description": "Contemporary style", "image": "/placeholder.svg"},
  {"title": "Kids Room", "description": "Fun and functional", "image": "/placeholder.svg"},
  {"title": "Guest Suite", "description": "Welcome your visitors", "image": "/placeholder.svg"}
]' WHERE section_key = 'gallery_items';

UPDATE homepage_content SET content = '[
  {"title": "Sectional", "description": "Flexible seating", "icon": "🛋️", "image": "/placeholder.svg"},
  {"title": "Loveseat", "description": "Perfect for two", "icon": "💕", "image": "/placeholder.svg"},
  {"title": "Sleeper Sofa", "description": "Space saving", "icon": "🛏️", "image": "/placeholder.svg"},
  {"title": "Recliner", "description": "Ultimate comfort", "icon": "🪑", "image": "/placeholder.svg"}
]' WHERE section_key = 'sofa_types';

UPDATE homepage_content SET content = '[
  {"title": "Premium Memory Foam", "price": "£509", "originalPrice": "£599", "image": "/mattress-image.svg", "badge": "Best Seller"},
  {"title": "Modern Platform Bed", "price": "£249", "originalPrice": "£299", "image": "/mattress-image.svg", "badge": "On Sale"},
  {"title": "Sectional Sofa", "price": "£764", "originalPrice": "£899", "image": "/sofa.jpeg", "badge": "Popular"},
  {"title": "Memory Foam Pillow", "price": "£67", "originalPrice": "£79", "image": "/mattress-image.svg", "badge": "New"}
]' WHERE section_key = 'trending_items';

UPDATE homepage_content SET content = '[
  {"title": "Add a Pillow", "description": "Complete your sleep setup", "image": "/placeholder.svg", "discount": "20%"},
  {"title": "Mattress Protector", "description": "Protect your investment", "image": "/placeholder.svg", "discount": "15%"},
  {"title": "Bedding Set", "description": "Luxury bedding", "image": "/placeholder.svg", "discount": "25%"},
  {"title": "Bedside Lamp", "description": "Perfect lighting", "image": "/placeholder.svg", "discount": "30%"}
]' WHERE section_key = 'promotional_cards';

UPDATE homepage_content SET content = '[
  {"title": "Mattress Buying Guide", "description": "How to choose the perfect mattress", "image": "/placeholder.svg", "readTime": "5 min"},
  {"title": "Bedroom Design Tips", "description": "Create your dream bedroom", "image": "/placeholder.svg", "readTime": "8 min"},
  {"title": "Sleep Health", "description": "Improve your sleep quality", "image": "/placeholder.svg", "readTime": "6 min"},
  {"title": "Furniture Care", "description": "Maintain your furniture", "image": "/placeholder.svg", "readTime": "4 min"}
]' WHERE section_key = 'guides';

-- ============================================================================
-- VERIFICATION QUERIES
-- ============================================================================

-- Check how many products we have in each category
SELECT 'Mattresses' as category, COUNT(*) as count FROM mattresses
UNION ALL
SELECT 'Beds' as category, COUNT(*) as count FROM beds
UNION ALL
SELECT 'Sofas' as category, COUNT(*) as count FROM sofas
UNION ALL
SELECT 'Pillows' as category, COUNT(*) as count FROM pillows
UNION ALL
SELECT 'Toppers' as category, COUNT(*) as count FROM toppers
UNION ALL
SELECT 'Bunkbeds' as category, COUNT(*) as count FROM bunkbeds;

-- Check brands
SELECT name, description FROM brands ORDER BY name;

-- Check homepage content sections
SELECT section_key, jsonb_array_length(content) as item_count FROM homepage_content ORDER BY section_key;
