export interface ProductRecord {
  id: number
  name: string
  brand: string
  brandColor: string
  badge: string
  badgeColor: string
  image: string
  rating: number
  reviewCount: number
  firmness: string
  firmnessLevel: number
  features: string[]
  originalPrice: number
  currentPrice: number
  savings: number
  freeDelivery: string
  setupService?: boolean
  setupCost?: number
  certifications: string[]
  sizes: string[]
  selectedSize?: string
  monthlyPrice?: number
  images?: string[]
  category: string
  type: string
  size: string
  comfortLevel: string
  inStore: boolean
  onSale: boolean
}

const getCategoryImage = (cat: string): string => {
  const map: Record<string, string> = {
    mattresses: 'https://images.unsplash.com/photo-1505693314120-0d443867891c?w=800&h=600&fit=crop',
    pillows: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&h=600&fit=crop',
    bedding: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800&h=600&fit=crop',
    'adjustable-bases': 'https://images.unsplash.com/photo-1505693314120-0d443867891c?w=800&h=600&fit=crop',
    'box-springs': 'https://images.unsplash.com/photo-1505693314120-0d443867891c?w=800&h=600&fit=crop',
    beds: 'https://images.unsplash.com/photo-1505693314120-0d443867891c?w=800&h=600&fit=crop',
    sofas: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&h=600&fit=crop',
    default: 'https://images.unsplash.com/photo-1505693314120-0d443867891c?w=800&h=600&fit=crop',
  }
  return map[cat] || map.default
}

export function getProductsByCategory(category: string): ProductRecord[] {
  const baseProducts: ProductRecord[] = [
    {
      id: 1,
      name: 'King Arthur Mattress',
      brand: 'ARTHUR SLEEP',
      brandColor: 'orange',
      badge: 'Best Seller',
      badgeColor: 'orange',
      image: getCategoryImage('mattresses'),
      rating: 4.8,
      reviewCount: 127,
      firmness: 'MEDIUM FIRM',
      firmnessLevel: 7,
      features: ['Bamboo cover', 'Motion isolation', 'Edge support', 'CertiPUR foam'],
      originalPrice: 499.0,
      currentPrice: 424.15,
      savings: 74.85,
      freeDelivery: 'Mon, 11 Aug',
      setupService: true,
      setupCost: 49,
      certifications: ['OEKO-TEX', 'CertiPUR-US', 'Made in UK', '100-Night Trial', '10-Year Warranty'],
      sizes: ['Single', 'Double', 'King', 'Super King'],
      selectedSize: 'King',
      monthlyPrice: 35,
      images: [
        'https://images.unsplash.com/photo-1505693314120-0d443867891c?w=800&h=600&fit=crop',
        'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&h=600&fit=crop',
        'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800&h=600&fit=crop',
        'https://images.unsplash.com/photo-1505693314120-0d443867891c?w=800&h=600&fit=crop',
      ],
      category: 'mattresses',
      type: 'Memory Foam',
      size: 'King Size',
      comfortLevel: 'Firm',
      inStore: true,
      onSale: true,
    },
    {
      id: 2,
      name: 'Dream Mirapocket 1000 Mattress',
      brand: 'SILENTNIGHT',
      brandColor: 'orange',
      badge: 'New Model',
      badgeColor: 'gray',
      image: getCategoryImage('mattresses'),
      rating: 4.0,
      reviewCount: 256,
      firmness: 'MEDIUM',
      firmnessLevel: 6,
      features: ['ECO COMFORT™', '1000 POCKET SPRINGS', '24CM DEPTH', 'Motion isolation'],
      originalPrice: 342.0,
      currentPrice: 290.7,
      savings: 51.3,
      freeDelivery: 'Tomorrow',
      setupService: false,
      certifications: ['OEKO-TEX', 'Made in UK', '100-Night Trial', '5-Year Warranty'],
      sizes: ['Single', 'Double', 'King', 'Super King'],
      selectedSize: 'Double',
      monthlyPrice: 25,
      images: [
        'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&h=600&fit=crop',
        'https://images.unsplash.com/photo-1505693314120-0d443867891c?w=800&h=600&fit=crop',
      ],
      category: 'mattresses',
      type: 'Spring',
      size: 'Double',
      comfortLevel: 'Medium',
      inStore: false,
      onSale: true,
    },
    {
      id: 3,
      name: 'Ice Arthur Mattress',
      brand: 'ARTHUR SLEEP',
      brandColor: 'orange',
      badge: 'Cooling',
      badgeColor: 'gray',
      image: getCategoryImage('mattresses'),
      rating: 4.5,
      reviewCount: 189,
      firmness: 'MEDIUM',
      firmnessLevel: 6,
      features: ['GEL FOAM', '3000 POCKET SPRINGS', '30CM DEPTH', 'Cooling', 'Edge support'],
      originalPrice: 559.0,
      currentPrice: 475.15,
      savings: 83.85,
      freeDelivery: 'Tomorrow',
      setupService: true,
      setupCost: 49,
      certifications: ['OEKO-TEX', 'CertiPUR-US', 'Made in UK', '100-Night Trial', '10-Year Warranty'],
      sizes: ['Single', 'Double', 'King', 'Super King'],
      selectedSize: 'King',
      monthlyPrice: 40,
      images: [
        'https://images.unsplash.com/photo-1505693314120-0d443867891c?w=800&h=600&fit=crop',
        'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&h=600&fit=crop',
        'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800&h=600&fit=crop',
      ],
      category: 'mattresses',
      type: 'Hybrid',
      size: 'King Size',
      comfortLevel: 'Medium',
      inStore: true,
      onSale: false,
    },
    {
      id: 4,
      name: 'FRIO 5-Sided Premium Cooling Mattress Protector',
      brand: 'MattressKing',
      brandColor: 'blue',
      badge: 'Best Seller',
      badgeColor: 'orange',
      image: getCategoryImage('bedding'),
      rating: 4.7,
      reviewCount: 500,
      firmness: 'N/A',
      firmnessLevel: 0,
      features: ['Cooling', 'Waterproof'],
      originalPrice: 90.0,
      currentPrice: 75.95,
      savings: 14.05,
      freeDelivery: 'Tomorrow',
      setupService: false,
      certifications: ['OEKO-TEX', 'Made in UK', '100-Night Trial'],
      sizes: ['Single', 'Double', 'King', 'Super King'],
      selectedSize: 'Queen',
      monthlyPrice: 8,
      images: ['https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800&h=600&fit=crop'],
      category: 'bedding',
      type: 'Mattress Protectors',
      size: 'Queen',
      comfortLevel: 'N/A',
      inStore: true,
      onSale: true,
    },
    {
      id: 5,
      name: 'Premium Smooth Waterproof Mattress Protector',
      brand: 'MattressKing',
      brandColor: 'blue',
      badge: 'Best Seller',
      badgeColor: 'orange',
      image: getCategoryImage('bedding'),
      rating: 4.5,
      reviewCount: 300,
      firmness: 'N/A',
      firmnessLevel: 0,
      features: ['Waterproof'],
      originalPrice: 55.0,
      currentPrice: 45.95,
      savings: 9.05,
      freeDelivery: 'Tomorrow',
      setupService: false,
      certifications: ['OEKO-TEX', 'Made in UK'],
      sizes: ['Single', 'Double', 'King', 'Super King'],
      selectedSize: 'Queen',
      monthlyPrice: 6,
      images: ['https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800&h=600&fit=crop'],
      category: 'bedding',
      type: 'Mattress Protectors',
      size: 'Queen',
      comfortLevel: 'N/A',
      inStore: false,
      onSale: true,
    },
    {
      id: 6,
      name: 'Encase HD 360° Mattress Protector',
      brand: 'MattressKing',
      brandColor: 'blue',
      badge: 'New',
      badgeColor: 'gray',
      image: getCategoryImage('bedding'),
      rating: 4.3,
      reviewCount: 150,
      firmness: 'N/A',
      firmnessLevel: 0,
      features: ['360 Protection'],
      originalPrice: 100.0,
      currentPrice: 84.95,
      savings: 15.05,
      freeDelivery: 'Tomorrow',
      setupService: false,
      certifications: ['OEKO-TEX', 'Made in UK'],
      sizes: ['Single', 'Double', 'King', 'Super King'],
      selectedSize: 'Queen',
      monthlyPrice: 9,
      images: ['https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800&h=600&fit=crop'],
      category: 'bedding',
      type: 'Mattress Protectors',
      size: 'Queen',
      comfortLevel: 'N/A',
      inStore: true,
      onSale: false,
    },
    {
      id: 7,
      name: 'Soft Washed Microfiber Sheets',
      brand: 'MattressKing',
      brandColor: 'blue',
      badge: 'Best Seller',
      badgeColor: 'orange',
      image: getCategoryImage('bedding'),
      rating: 4.6,
      reviewCount: 400,
      firmness: 'N/A',
      firmnessLevel: 0,
      features: ['Soft', 'Wrinkle-Free'],
      originalPrice: 50.0,
      currentPrice: 44.95,
      savings: 5.05,
      freeDelivery: 'Tomorrow',
      setupService: false,
      certifications: ['OEKO-TEX', 'Made in UK'],
      sizes: ['Single', 'Double', 'King', 'Super King'],
      selectedSize: 'Queen',
      monthlyPrice: 5,
      images: ['https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800&h=600&fit=crop'],
      category: 'bedding',
      type: 'Sheets',
      size: 'Queen',
      comfortLevel: 'N/A',
      inStore: true,
      onSale: true,
    },
    {
      id: 8,
      name: 'Memory Foam Pillow',
      brand: 'MattressKing',
      brandColor: 'blue',
      badge: 'Comfort',
      badgeColor: 'gray',
      image: getCategoryImage('pillows'),
      rating: 4.5,
      reviewCount: 250,
      firmness: 'Medium',
      firmnessLevel: 6,
      features: ['Memory Foam', 'Pressure Relief'],
      originalPrice: 60.0,
      currentPrice: 49.99,
      savings: 10.01,
      freeDelivery: 'Tomorrow',
      setupService: false,
      certifications: ['OEKO-TEX', 'Made in UK'],
      sizes: ['Standard', 'Queen', 'King'],
      selectedSize: 'Standard',
      monthlyPrice: 6,
      images: ['https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&h=600&fit=crop'],
      category: 'pillows',
      type: 'Memory Foam',
      size: 'Standard',
      comfortLevel: 'Medium',
      inStore: true,
      onSale: false,
    },
    {
      id: 9,
      name: 'Adjustable Base Pro',
      brand: 'Adjustable Sleep',
      brandColor: 'blue',
      badge: 'Smart',
      badgeColor: 'gray',
      image: getCategoryImage('adjustable-bases'),
      rating: 4.9,
      reviewCount: 600,
      firmness: 'N/A',
      firmnessLevel: 0,
      features: ['Massage', 'USB Ports', 'Zero Gravity'],
      originalPrice: 1500.0,
      currentPrice: 1299.0,
      savings: 201.0,
      freeDelivery: 'Tomorrow',
      setupService: true,
      setupCost: 99,
      certifications: ['Made in UK', '5-Year Warranty'],
      sizes: ['Single', 'Double', 'King', 'Super King'],
      selectedSize: 'Queen',
      monthlyPrice: 65,
      images: ['https://images.unsplash.com/photo-1505693314120-0d443867891c?w=800&h=600&fit=crop'],
      category: 'adjustable-bases',
      type: 'Premium',
      size: 'Queen',
      comfortLevel: 'N/A',
      inStore: true,
      onSale: true,
    },
    {
      id: 10,
      name: 'Heavy Duty Mattress',
      brand: 'Strong Sleep',
      brandColor: 'orange',
      badge: 'Durable',
      badgeColor: 'orange',
      image: getCategoryImage('mattresses'),
      rating: 4.7,
      reviewCount: 300,
      firmness: 'Firm',
      firmnessLevel: 9,
      features: ['Heavy Duty', 'Extra Support', 'Edge support'],
      originalPrice: 700.0,
      currentPrice: 620.0,
      savings: 80.0,
      freeDelivery: 'Tomorrow',
      setupService: true,
      setupCost: 49,
      certifications: ['OEKO-TEX', 'Made in UK', '100-Night Trial', '10-Year Warranty'],
      sizes: ['Single', 'Double', 'King', 'Super King'],
      selectedSize: 'King',
      monthlyPrice: 55,
      images: ['https://images.unsplash.com/photo-1505693314120-0d443867891c?w=800&h=600&fit=crop'],
      category: 'mattresses',
      type: 'Hybrid',
      size: 'King Size',
      comfortLevel: 'Firm',
      inStore: true,
      onSale: false,
    },
    {
      id: 11,
      name: 'Cooling Gel Pillow',
      brand: 'Cool Dreams',
      brandColor: 'blue',
      badge: 'Cooling',
      badgeColor: 'gray',
      image: getCategoryImage('pillows'),
      rating: 4.6,
      reviewCount: 180,
      firmness: 'Soft',
      firmnessLevel: 3,
      features: ['Cooling Gel'],
      originalPrice: 75.0,
      currentPrice: 65.0,
      savings: 10.0,
      freeDelivery: 'Tomorrow',
      setupService: false,
      certifications: ['OEKO-TEX', 'Made in UK'],
      sizes: ['Standard', 'Queen', 'King'],
      selectedSize: 'Queen',
      monthlyPrice: 8,
      images: ['https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&h=600&fit=crop'],
      category: 'pillows',
      type: 'Cooling Gel',
      size: 'Queen',
      comfortLevel: 'Soft',
      inStore: false,
      onSale: true,
    },
    {
      id: 12,
      name: 'Organic Cotton Sheets',
      brand: 'Eco Sleep',
      brandColor: 'blue',
      badge: 'Organic',
      badgeColor: 'gray',
      image: getCategoryImage('bedding'),
      rating: 4.8,
      reviewCount: 450,
      firmness: 'N/A',
      firmnessLevel: 0,
      features: ['Organic', 'Hypoallergenic'],
      originalPrice: 120.0,
      currentPrice: 99.0,
      savings: 21.0,
      freeDelivery: 'Tomorrow',
      setupService: false,
      certifications: ['OEKO-TEX', 'Made in UK', 'Organic Certified'],
      sizes: ['Single', 'Double', 'King', 'Super King'],
      selectedSize: 'King',
      monthlyPrice: 10,
      images: ['https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800&h=600&fit=crop'],
      category: 'bedding',
      type: 'Sheets',
      size: 'King',
      comfortLevel: 'N/A',
      inStore: true,
      onSale: false,
    },
  ]

  const generated: ProductRecord[] = Array.from({ length: 20 }, (_, i) => ({
    id: i + 13,
    name: `Comfort ${category} ${i + 1}`,
    brand: 'SLEEPWELL',
    brandColor: 'blue',
    badge: 'Popular',
    badgeColor: 'gray',
    image: getCategoryImage(category),
    rating: 4.2 + ((i % 6) * 0.1),
    reviewCount: 50 + ((i * 25) % 500),
    firmness: ['SOFT', 'MEDIUM', 'FIRM'][i % 3],
    firmnessLevel: [3, 6, 8][i % 3],
    features: ['Premium Quality', 'Long Lasting', 'Comfortable', 'Motion Isolation', 'Edge Support'],
    originalPrice: 300 + ((i * 20) % 400),
    currentPrice: 250 + ((i * 15) % 300),
    savings: 50 + ((i * 5) % 100),
    freeDelivery: 'Tomorrow',
    setupService: i % 2 === 0,
    setupCost: i % 2 === 0 ? 49 : undefined,
    certifications: ['OEKO-TEX', 'Made in UK', '100-Night Trial'],
    sizes: ['Single', 'Double', 'King', 'Super King'],
    selectedSize: ['Single', 'Double', 'King', 'Super King'][i % 4],
    monthlyPrice: Math.floor((250 + ((i * 15) % 300)) / 12),
    images: [getCategoryImage(category)],
    category,
    type: ['Memory Foam', 'Spring', 'Hybrid', 'Latex', 'Adjustable'][i % 5],
    size: ['Twin', 'Twin XL', 'Full', 'Queen', 'King', 'California King'][i % 6],
    comfortLevel: ['Soft', 'Medium', 'Firm', 'Extra Firm'][i % 4],
    inStore: i % 2 === 0,
    onSale: i % 3 === 0,
  }))

  // Combine tailored generated items for the requested category with base products
  return [...baseProducts.filter(p => p.category === category), ...generated]
}

export function getProductById(category: string, id: number): ProductRecord | undefined {
  return getProductsByCategory(category).find(p => p.id === id)
}


